lib/0001_retrieve-secrets.sh

If the `credentials` in `VCAP_SERVICES` includes a value of type Fixnum, then the line of code that checks for blank credentials and excludes them from the environment variables passed to Summon will error.
This PR fixes that line of code so it will convert the value to a string before checking if it is empty.
[Jenkins build](https://jenkins.conjur.net/job/cyberark--cloudfoundry-conjur-buildpack/job/fixnum-blank-var-bug-fix/1/)

Buildpack causes error when credentials include Fixnum

---

README.md
bin/supply
ci/features/profile_d.feature
ci/features/step_definitions/profile_d_steps.rb
ci/features/step_definitions/supply_steps.rb
ci/features/supply.feature

Connected to #22 
This PR updates the Conjur buildpack to install the secret retrieval script into `profile.d` instead of `.profile.d`.
It also updates the README to improve the examples for using the buildpack.
Jenkins build: https://jenkins.conjur.net/job/cyberark--cloudfoundry-conjur-buildpack/job/22-supply-profile-dir/

Update supply script to use correct profile directory

---

secrets.yml

Connected to https://github.com/conjurinc/cloudfoundry-conjur-tile/issues/32
This PR removes the CI environment URLs from `secrets.yml` and pulls them via Summon as well.

Fetch CI environment URLs via summon

---

CHANGELOG.md
ci/features/step_definitions/common_steps.rb
conjur-env/main.go

Close #48 
`VCAP_SERVICES` may contain service credentials for other services
in addition to `cyberark-conjur`. If any of these services define credential
fields that collide with Conjur's, its possible for the unmarshalling to fail
because of JSON type errors.
We resolve this by updating our JSON marshalling to ignore all service
keys other than `cyberark-conjur`.

Update the VCAP_SERVICES unmarshalling to ignore other services

---

Jenkinsfile

This uses new pipeline library functions to add the IP address of the Jenkins agent to the
AWS prefix list used to limit access to the PCF cluster and remove access once completed.

Update to add IP to list for security group access

---

.github/workflows/unit-tests.yml

Updates actions/setup-go to use v2, used in running unit tests via Github Actions. Some commands have been deprecated in Github actions, see https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/, v2 addresses this.
N/A

Update actions/setup-go to use v2

---

.github/workflows/copy-release-to-latest-branch.yml
CHANGELOG.md
README.md

- Add automation to auto-archive tags in the latest branch
- Update README to recommend users refer to the latest branch or a specific tag
when using the online buildpack functionality
To see how the action works in action, you can review this [test run](https://github.com/conjurinc/playroom/actions/runs/472382983) that resulted in a [PR being opened](https://github.com/conjurinc/playroom/pull/154) post-tag.
Resolves #101

Update recommendations for online buildpack usage

---

CHANGELOG.md

This change adds a `Removed` entry to the CHANGELOG.md to indicate
that support for using the buildpack with Conjur v4 is no longer
available.
No code changes are required to remove Conjur v4 support since the
code and tests are largely agnostic of which Conjur version it is
working with. The conjur-dev code and the tests use:
- cyberark/conjur latest Docker image
- cyberark/conjur-api-go v0.6.0
- cyberark/summon v0.8.2 (secretsyml module)
There is one location where the credentials for the Conjur API is
set for Conjur v5:
tests/integration/features/step_definitions/common_steps.rb, line 59.
Resolves #86

Removes support for Conjur Enterprise v4

---

tests/retrieve-secrets/start

We ran into a small race condition when deleting the BATS dependencies before downloading them.
Thus, we've removed those lines, since they don't need to be removed from an empty environment before
we run the script.
Resolves #[relevant GitHub issues, eg 76]

Remove 'rm' lines in secret retrieval start script

---

CHANGELOG.md
README.md
conjur-env/main.go
conjur-env/main_test.go
tests/integration/apps/php/manifest-env.yml.template
tests/integration/features/profile_d.feature
tests/integration/features/step_definitions/common_steps.rb
tests/integration/features/support/cf_helper.rb

`SUMMON_ENV` is now a configurable variable in buildpack
manifests, allowing the user to define multiple environments in their
`secrets.yml`. This allows for configurable deployments using the same
`secrets.yml` file.
Note: Rubocop requests we use "meaningful" heredoc labels, e.g. anything other than EOS
Resolves #44

Add support for summon evironments

---

CHANGELOG.md

Updates link in changelog to be absolute instead of relative, so that downstream release notes aggregation has valid links.
n/a

Update links in CHANGELOG

---

Dockerfile.packager
conjur-env/go.mod
conjur-env/go.sum

When `git install` is ran from a non-module directory, it needs a version. In this case,
`@latest`.
Additionally, some of our `go.mod` dependencies were missing correct `go.sum` entries
Resolves #113

Add @latest to go install command

---

CHANGELOG.md
lib/0001_retrieve-secrets.sh
tests/retrieve-secrets/stop
tests/retrieve-secrets/test

This change fixes an issue whereby:
- If the `0001_retrieve-secrets.sh` script is being sourced/called from another script (as is done in production)
- And an error occurs in parsing the variable settings in the `conjur-env` binary output (e.g. for an invalid variable name)
- Then the fields of error messages being generated by the `0001_retrieve-secrets.sh` script were getting scrambled and the error message was getting concatenated multiple times.
Here is an example of an error that was getting generated:
```
./tmp/0001_retrieve-secrets.sh: Error on line ./tmp/0001_retrieve-secrets.sh: Unable to export `/tmp/bats-run-1/bats.111.src`; value may not be a valid identifier/opt/bats/lib/bats-core/test_functions.bash: Error on line /tmp/bats-run-1/bats.111.src: Unable to export …
```

Fixes scrambled error output when call to retrieve script is nested

---

Dockerfile.packager
Jenkinsfile
ci/get_compute_ip
ci/secrets.yml
ci/test_conjur-env
ci/test_e2e
ci/test_unit
ci/utils
tests/docker-compose.yml
tests/integration/apps/java/bin/build

Previously infra provided TAS clusters in AWS. This commit switches
to using clusters provided by VMWare. These clusters are single use,
allocated and deallocated during the pipeline.
Related: conjurinc/ops#857

Use VMWare ISV Service for CI clusters

---

CHANGELOG.md
ci/start_dev_environment
conjur-env/Dockerfile
lib/install_go.sh
manifest.yml
tests/retrieve-secrets/Dockerfile
tests/retrieve-secrets/go.mod

Upgrade Golang Dockerfile base images to fix OpenSSL CVE-2022-0778 and CVE-2022-1292.
- Upgrade Dockerfile base images to `golang:1.17.9-stretch`, which uses OpenSSL v1.1.0l
- Upgrade project Go version to 1.17
- Remove deprecated Go 1.14 and 1.15 dependencies
CyberArk internal issue link: [CONJSE-1310](https://ca-il-jira.il.cyber-ark.com:8443/browse/CONJSE-1310)
merged.*
changes, or

Upgrade project Golang version to 1.17

---

CHANGELOG.md
conjur-env/go.mod

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Remove Snyk's perceived indirect dependency on gopkg.in/yaml.v2 v2.2.2
Added replace in conjur-env/go.mod to prune v2.2.2 and replace it with v2.2.8
merged.*
changes, or
- [] Docs (e.g. `README`s) were updated in this PR

Replace gopkg.in/yaml.v2 v2.2.2 with v2.2.8

---

Jenkinsfile

TAS 3.0 was recently released which broke deployment scripts, so the latest 2.x will be used until 3.0 compatibility is complete.
Related: ONYX-26801

Pin CI TAS Environment to 2.13

---

CHANGELOG.md
tests/integration/apps/java/pom.xml

Signed-off-by: Andy Tinkham <andy.tinkham@cyberark.com>
Upgrade Spring Boot Starter Web to 2.7.5 to resolve some vulnerable indirect dependencies

Update java test app to Spring Boot 2.7.5

---

CHANGELOG.md
NOTICES.txt
conjur-env/go.mod
conjur-env/go.sum
tests/integration/apps/ruby/Gemfile
tests/integration/apps/ruby/Gemfile.lock

Update Summon to v0.9.5 to address golang.org/x/net and golang.org/x/text vulnerabilities.
Update Summon in go.mod.
merged.*
changes, or

Update summon to v0.9.5

---

tests/Dockerfile

Fix Jenkins build. Logs:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
ruby2.5-dev : Depends: libruby2.5 (= 2.5.1-1ubuntu1.16) but 2.5.1-1ubuntu1.16+esm1 is to be installed
Recommends: ruby2.5-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Use Brightbox's Ruby 2.5 packages instead defaults.
N/A
merged.*
changes, or

Use Brightbox Ruby package in test Dockerfile

---

CHANGELOG.md
Jenkinsfile
ci/start_dev_environment
lib/install_go.sh
manifest.yml
tests/Dockerfile
tests/docker-compose.yml

Update the buildpack to work with the latest TAS v3, v4 and v5.
- Maintain support for `cflinuxfs3` stack (used by TAS v3)
- Add support for `cflinuxfs4` stack (used by TAS v4 and v5)
- Bump project Go version from 1.17.9 to 1.20.9, with support for 1.21.2
CyberArk internal issue ID: CNJR-2670
merged.*
changes, or

Add support for TAS 3.0, 4.0 and 5.0

---

ci/start_dev_environment
ci/test_e2e
ci/test_integration
ci/utils
conjur-env/build.sh
conjur-env/docker-compose.yml
tests/docker-compose.yml
tests/integration/apps/ruby/Gemfile
tests/integration/apps/ruby/Gemfile.lock
tests/integration/apps/ruby/Procfile
tests/integration/features/integration.feature
tests/integration/features/step_definitions/integration_steps.rb
tests/retrieve-secrets/README.md
tests/retrieve-secrets/docker-compose.yml
tests/retrieve-secrets/start
tests/retrieve-secrets/stop

Fix Jenkins pipeline by using Docker Compose v2
Replaces calls to `docker-compose` with `docker compose`
CyberArk internal issue ID: CNJR-2127
merged.*
changes, or

CNJR-2127: Use Docker Compose v2
